### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by AlexxNica** [apache/incubator-openwhisk-slackinvite#10]
The following link is not working (404) and needs to be updated:
https://openwhisk.github.io/openwhisk-slackinvite/

Where:
- Repo Description
- README.md

**Comment by dubeejw** [comment]
It appears that https://openwhisk.github.io no longer works. @csantanapr

**Comment by AlexxNica** [comment]
I can send a PR, the correct URL is https://openwhisk.apache.org/slack.html;

The only thing I can't change is the repository description, though.

**Comment by csantanapr** [comment]
Yeah go ahead and send update for the url, the live page moved to openwhisk.apache.org I can open a ticket against Infra to update the description.
